spring.application.name=gateway-servic

server.port=8765

#Self registration pattern
eureka.client.service-url.default-zone=http://localhost:8761/eureka
#Ideal para ambientes conteinerizados
eureka.instance.prefer-ip-address=true
#Personaliza��o de ID de cada instancia
eureka.instance.instance-id=${spring.application.name}:${server.port}
#Indicar que o Service Registry deve validar a sa�de do servi�o atravez do actuator, e n�o somente Heartbeat
#OPCIONAL - valor Default = True
eureka.client.healthcheck.enabled=true

#Configura��o minima para atua��o com o Service Registry de forma consciente
management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events
#ATEN��O: Cuidado ao expor esses dados
#Exibir informa��es de sa�de da app
management.endpoint.health.show-details=always
#Exibir informa��es no endpoint /actuator/info
management.info.env.enabled=true

#personaliza��o de informa��es do endpoint /actuator/info
info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=Guilherme Tadeu Castellani
#personaliza��o de Metadatas
eureka.instance.metadata-map.github.repo=GuilhermeTCastellani/microservices-java

#Definir a utiliza��o das Probes Livenesse Readdiness + exibi��o de informa��es e componentes diversos (DEFAULT = opcional)
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true