spring.application.name=greeting-service
server.port=8080

greeting-service.greeting=Ola
greeting-service.default-name=Mundo

spring.profiles.active=es

#Self registration pattern
eureka.client.service-url.default-zone=http://localhost:8761/eureka
#Ideal para ambientes conteinerizados
eureka.instance.prefer-ip-address=true
#Personalização de ID de cada instancia
eureka.instance.instance-id=${spring.application.name}:${server.port}
#Indicar que o Service Registry deve validar a saúde do serviço atravez do actuator, e não somente Heartbeat
#OPCIONAL - valor Default = True
eureka.client.healthcheck.enabled=true

#Configuração minima para atuação com o Service Registry de forma consciente
management.endpoints.web.exposure.include=health,info,metrics
#ATENÇÃO: Cuidado ao expor esses dados
#Exibir informações de saúde da app
management.endpoint.health.show-details=always
#Exibir informações no endpoint /actuator/info
management.info.env.enabled=true

#personalização de informações do endpoint /actuator/info
info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=Guilherme Tadeu Castellani
#personalização de Metadatas
eureka.instance.metadata-map.github.repo=https://github.com/GuilhermeTCastellani/microservices-java.git

#Definir a utilização das Probes Livenesse Readdiness + exibição de informações e componentes diversos (DEFAULT = opcional)
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true