spring.application.name=product-service
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost/db_product
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.flyway.locations=classpath:db_migration

#Self registration pattern
eureka.client.service-url.default-zone=http://localhost:8761/eureka
#Ideal para ambientes conteinerizados
eureka.instance.prefer-ip-address=true
#Personalização de ID de cada instancia
eureka.instance.instance-id=${spring.application.name}:${server.port}
#Indicar que o Service Registry deve validar a saúde do serviço atravez do actuator, e não somente Heartbeat
#OPCIONAL - valor Default = True
eureka.client.healthcheck.enabled=true

#Configuração minima para atuação com o Service Registry de forma consciente
management.endpoints.web.exposure.include=health,info,metrics, circuit-breakers, circuit-breakers-events
#ATENÇÃO: Cuidado ao expor esses dados
#Exibir informações de saúde da app
management.endpoint.health.show-details=always
#Exibir informações no endpoint /actuator/info
management.info.env.enabled=true

#personalização de informações do endpoint /actuator/info
info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=Guilherme Tadeu Castellani
#personalização de Metadatas
eureka.instance.metadata-map.github.repo=https://github.com/GuilhermeTCastellani/microservices-java.git

#Definir a utilização das Probes Livenesse Readdiness + exibição de informações e componentes diversos (DEFAULT = opcional)
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true

# RESILIENCE PATTERN - TIMEOUT
# Estabelecer conection = 1seg
spring.cloud.openfeign.client.config.currency-service.connect-timeout=1000
# Processar e receber dados
spring.cloud.openfeign.client.config.currency-service.read-timeout=3000

# RESILIENCE PATTERNS - RETRY
# Quantidade maxima de tentativas (1try + 2tryes)
resilience4j.retry.instances.currency-service.max-attempts=3
# Tempo de espera entre as tentativas
resilience4j.retry.instances.currency-service.wait-duration=500ms
# Ativa o recuo exponencial (Exponential Backoff)
resilience4j.retry.instances.currency-service.enable-exponential-backoff=true
# Multiplicador do tempo de espera (1try = 500ms -> 2try = 1000ms, ...)
resilience4j.retry.instances.currency-service.exponential-backoff-multiplier=2.0
# Ativa a variação aleatoria do tempo de espera (jitter)
resilience4j.retry.instances.currency-service.enable-randomized-wait=true
# Fator do jitter (Aplica uma flutuação aleatoria de até 50% para mais ou menos)
resilience4j.retry.instances.currency-service.randomized-wait-factor=0.5

# Regra de Excessão: IGNORAR/RETENTAR (um ou outro)
# IGNORAR (Evita desperdicio de recusros em falhas do cliente)
# ignora qualquer erro HTTP da familia 4xx (400, 401, 403, 404, ...)
resilience4j.retry.instances.currency-service.ignore-exceptions[0]=feign.FeignException$FeignClientException


# RESILIENCE PATTERNS - CACHING
# Configura o tipo de cache. Para cache em memória o caffeine é considerado com melhor desempenho
spring.cache.type=caffeine
# Configurações do cache = 500 objetosno máximo e com um tempo de expiração de 15 seg
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=15s

# RESILIENCE PATTERN - CIRCUIT BREAKER
# Habilita o Circuit Breker do Resilience4j no OpenFeign
spring.cloud.openfeign.circuitbreaker.enabled=true
# Habilita o indicador de saude para esta instancia do circuit breaker
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.register-health-indicator=true
# Número de chamadas na janela deslizante para calcular a taxa de falhas
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.sliding-window-size=10
# Número minimo de chamadas antes de calcular a taxa de falhas
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.minimum-number-of-calls=5
# Percentual maximo de chamadas antes de abrir o circuito
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.failure-rate-threshold=50
# Tempo em que o circuito permane aberto antes de ficar meio-aberto
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.wait-duration-in-open-state=30s
# Numero de chamadas permitidas no estado meio-aberto para testar
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.permitted-number-of-calls-in-half-open-state=3
# Ativa a transição automatica de aberto para meio-aberto sem esperar chamada
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.automatic-transition-from-open-to-half-open-enabled=true

# Habilita o actuator monitorar a saúde em conjunto com o circuit breaker
management.health.circuitbreakers.enabled=true

# Faz o OpenFeign usar o nome do microserviço como ID ... dessa forma sincroniza o retry com o circuit breaker
spring.cloud.openfeign.circuitbreaker.group.enabled=true